[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'

[profile.suave]
whitelist=['*']
service_alias = { holesky = "https://ethereum-holesky-rpc.publicnode.com" }
eth_backend = "execution"
