name: CI

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install suave-geth
        uses: flashbots/suave-toolchain@v0.1
      
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install Forge dependencies
        run: forge install

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test